a=int(input("Enter your first number=="))
b=int(input("Enter your second  number=="))
print("Addition of both numbers is:",a+b)
print("Subtraction of both numbers is:",a-b)
print("Multiplication of both numbers is:",a*b)
print("Division of both numbers is:",a/b)
print("floor division of both numbers is:",a//b)
print("modulo of both numbers is:",a%b)
print("power of a number:",a**b)